# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Spellsheets — TL;DR 开发者的速查文档
description: >- # this means to ignore newlines until "baseurl:"
  一个滑稽的开发者速查集合。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spellsheets.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  zhshch2002

# Build settings
theme: minima
whitelist:
  - jekyll-redirect-from
  - jekyll-github-metadata

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata

exclude:
  - .babelrc
  - .cache
  - CNAME
  - CONTRIBUTING.md
  - cssnano.config.js
  - docker_compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - vendor
  - webpack.config.js
  - yarn-error.log
  - yarn.lock

# Markdown

highlighter: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true

# Defaults

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
      og_type: article
      type: article
      category: "Others"
      excerpt_separator: "<!--more-->"
      prism_languages: []

repository: zhshch2002/spellsheets