name: Build and test
on: 
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with: { node-version: '12.x' }

      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with: { ruby-version: '2.7.1' }

      - name: Setup dependencies
        run: |
          yarn --frozen-lockfile
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - run: yarn build
      
      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: s3-cn-south-1
          bucket: spellsheets
          # exclude: .cache,test
          dist: _site
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_KEYID }}
          UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}
